# Base
from app.models.base import TimestampMixin

# Enums
from app.models.enums import CardState, QuizType, SessionStatus

# Schemas (DTOs)
from app.models.schemas import (
    AccuracyByPeriod,
    AnswerRequest,
    AnswerResponse,
    AvailableCards,
    CardAllocation,
    CardRequest,
    CardResponse,
    CategorySelectionState,
    ClozeQuestion,
    DailyGoalRead,
    DailyGoalStatus,
    DeckCreate,
    DeckDetailRead,
    DeckRead,
    DecksListResponse,
    DeckUpdate,
    DeckWithProgressRead,
    DisplayItem,
    DueCardSummary,
    FavoriteCreate,
    FavoriteRead,
    GetSelectedDecksResponse,
    NewCardsCountRead,
    ProfileConfigRead,
    ProfileConfigUpdate,
    ProfileLevelRead,
    ProfileRead,
    ProfileUpdate,
    ReviewRequest,
    SelectDecksRequest,
    SelectDecksResponse,
    SelectedDeckInfo,
    SelectedDecksSummary,
    SessionCompleteRequest,
    SessionCompleteResponse,
    SessionPreviewRequest,
    SessionPreviewResponse,
    SessionStartRequest,
    SessionStartResponse,
    SessionSummary,
    StatsAccuracyRead,
    StatsHistoryItem,
    StatsHistoryRead,
    StatsHistorySummary,
    StreakInfo,
    StreakRead,
    StudyCard,
    StudyOverviewResponse,
    TodayProgressRead,
    TodayStatsRead,
    TodayVocabularyStats,
    TotalLearnedRead,
    UserCardProgressCreate,
    UserCardProgressRead,
    UserSelectedDeckCreate,
    UserSelectedDeckRead,
    VocabularyCardCreate,
    VocabularyCardRead,
    VocabularyCardUpdate,
    XPInfo,
)

# Tables (DB Models) - includes Base classes
from app.models.tables import (
    Deck,
    DeckBase,
    Favorite,
    Profile,
    ProfileBase,
    StudySession,
    StudySessionBase,
    UserCardProgress,
    UserCardProgressBase,
    UserSelectedDeck,
    VocabularyCard,
    VocabularyCardBase,
)

__all__ = [
    # Base
    "TimestampMixin",
    # Enums
    "CardState",
    "SessionStatus",
    "QuizType",
    # Tables
    "Profile",
    "VocabularyCard",
    "UserCardProgress",
    "Deck",
    "Favorite",
    "UserSelectedDeck",
    "StudySession",
    # Base classes (from tables)
    "ProfileBase",
    "VocabularyCardBase",
    "UserCardProgressBase",
    "DeckBase",
    "StudySessionBase",
    # Profile Schemas
    "ProfileRead",
    "ProfileUpdate",
    "DailyGoalRead",
    "StreakRead",
    "ProfileConfigRead",
    "ProfileConfigUpdate",
    "ProfileLevelRead",
    # VocabularyCard Schemas
    "VocabularyCardCreate",
    "VocabularyCardRead",
    "VocabularyCardUpdate",
    # UserCardProgress Schemas
    "UserCardProgressCreate",
    "UserCardProgressRead",
    "ReviewRequest",
    "TodayProgressRead",
    "NewCardsCountRead",
    # Deck Schemas
    "DeckCreate",
    "DeckRead",
    "DeckUpdate",
    "DeckWithProgressRead",
    "DeckDetailRead",
    "DecksListResponse",
    # Favorite Schemas
    "FavoriteCreate",
    "FavoriteRead",
    # UserSelectedDeck Schemas
    "UserSelectedDeckCreate",
    "UserSelectedDeckRead",
    "SelectDecksRequest",
    "SelectDecksResponse",
    "SelectedDeckInfo",
    "GetSelectedDecksResponse",
    "SelectedDecksSummary",
    "DisplayItem",
    "CategorySelectionState",
    # Stats Schemas
    "TotalLearnedRead",
    "StatsHistoryRead",
    "StatsHistoryItem",
    "StatsHistorySummary",
    "StatsAccuracyRead",
    "AccuracyByPeriod",
    "TodayStatsRead",
    "TodayVocabularyStats",
    # Study Session Schemas
    "SessionStartRequest",
    "SessionStartResponse",
    "CardRequest",
    "CardResponse",
    "StudyCard",
    "ClozeQuestion",
    "AnswerRequest",
    "AnswerResponse",
    "SessionCompleteRequest",
    "SessionCompleteResponse",
    "SessionSummary",
    "StreakInfo",
    "DailyGoalStatus",
    "XPInfo",
    # Study Overview Schemas
    "DueCardSummary",
    "StudyOverviewResponse",
    # Session Preview Schemas
    "AvailableCards",
    "CardAllocation",
    "SessionPreviewRequest",
    "SessionPreviewResponse",
]
