# Base
from app.models.base import TimestampMixin

# Enums
from app.models.enums import CardState, ChatRole, QuizType, SessionStatus

# Schemas (DTOs)
from app.models.schemas import (
    AccuracyByPeriod,
    AnswerRequest,
    AnswerResponse,
    CardRequest,
    CardResponse,
    ClozeQuestion,
    DailyGoalRead,
    DailyGoalStatus,
    DeckCreate,
    DeckDetailRead,
    DeckRead,
    DecksListResponse,
    DeckUpdate,
    DeckWithProgressRead,
    DueCardSummary,
    FavoriteCreate,
    FavoriteRead,
    GetSelectedDecksResponse,
    NewCardsCountRead,
    ProfileConfigRead,
    ProfileConfigUpdate,
    ProfileLevelRead,
    ProfileRead,
    ProfileUpdate,
    ReviewRequest,
    SelectDecksRequest,
    SelectDecksResponse,
    SelectedDeckInfo,
    SessionCompleteRequest,
    SessionCompleteResponse,
    SessionStartRequest,
    SessionStartResponse,
    SessionSummary,
    StatsAccuracyRead,
    StatsHistoryItem,
    StatsHistoryRead,
    StreakInfo,
    StreakRead,
    StudyCard,
    StudyOverviewResponse,
    TodayProgressRead,
    TutorHistoryResponse,
    TutorMessageRead,
    TutorMessageRequest,
    TutorMessageResponse,
    TutorStartResponse,
    UserCardProgressCreate,
    UserCardProgressRead,
    UserSelectedDeckCreate,
    UserSelectedDeckRead,
    VocabularyCardCreate,
    VocabularyCardRead,
    VocabularyCardUpdate,
    XPInfo,
)

# Tables (DB Models) - includes Base classes
from app.models.tables import (
    Deck,
    DeckBase,
    Favorite,
    Profile,
    ProfileBase,
    StudySession,
    StudySessionBase,
    UserCardProgress,
    UserCardProgressBase,
    UserSelectedDeck,
    VocabularyCard,
    VocabularyCardBase,
    WordTutorMessage,
    WordTutorMessageBase,
    WordTutorThread,
    WordTutorThreadBase,
)

__all__ = [
    # Base
    "TimestampMixin",
    # Enums
    "CardState",
    "ChatRole",
    "SessionStatus",
    "QuizType",
    # Tables
    "Profile",
    "VocabularyCard",
    "UserCardProgress",
    "Deck",
    "Favorite",
    "UserSelectedDeck",
    "StudySession",
    "WordTutorThread",
    "WordTutorMessage",
    # Base classes (from tables)
    "ProfileBase",
    "VocabularyCardBase",
    "UserCardProgressBase",
    "DeckBase",
    "StudySessionBase",
    "WordTutorThreadBase",
    "WordTutorMessageBase",
    # Profile Schemas
    "ProfileRead",
    "ProfileUpdate",
    "DailyGoalRead",
    "StreakRead",
    "ProfileConfigRead",
    "ProfileConfigUpdate",
    "ProfileLevelRead",
    # VocabularyCard Schemas
    "VocabularyCardCreate",
    "VocabularyCardRead",
    "VocabularyCardUpdate",
    # UserCardProgress Schemas
    "UserCardProgressCreate",
    "UserCardProgressRead",
    "ReviewRequest",
    "TodayProgressRead",
    "NewCardsCountRead",
    # Deck Schemas
    "DeckCreate",
    "DeckRead",
    "DeckUpdate",
    "DeckWithProgressRead",
    "DeckDetailRead",
    "DecksListResponse",
    # Favorite Schemas
    "FavoriteCreate",
    "FavoriteRead",
    # UserSelectedDeck Schemas
    "UserSelectedDeckCreate",
    "UserSelectedDeckRead",
    "SelectDecksRequest",
    "SelectDecksResponse",
    "SelectedDeckInfo",
    "GetSelectedDecksResponse",
    # Stats Schemas
    "StatsHistoryRead",
    "StatsHistoryItem",
    "StatsAccuracyRead",
    "AccuracyByPeriod",
    # Study Session Schemas
    "SessionStartRequest",
    "SessionStartResponse",
    "CardRequest",
    "CardResponse",
    "StudyCard",
    "ClozeQuestion",
    "AnswerRequest",
    "AnswerResponse",
    "SessionCompleteRequest",
    "SessionCompleteResponse",
    "SessionSummary",
    "StreakInfo",
    "DailyGoalStatus",
    "XPInfo",
    # Study Overview Schemas
    "DueCardSummary",
    "StudyOverviewResponse",
    # Tutor Schemas
    "TutorMessageRequest",
    "TutorStartResponse",
    "TutorMessageResponse",
    "TutorMessageRead",
    "TutorHistoryResponse",
]
